/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import controller.ItemController;
import controller.TransactionController;
import model.Item;
import model.Transaction;
import model.TransactionDetail;

import java.awt.event.ActionEvent;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Hasitha
 */
public class SalesPanel extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SalesPanel.class.getName());

    /**
     * Creates new form SalesPanel
     */
    public SalesPanel() {
    initComponents();

    cartTableModel = (DefaultTableModel) cartTable.getModel();
    cartTableModel.setRowCount(0);
    quantitySpinner.setValue(1);

    loadItems();
}
    
    private void loadItems() {
    availableItems = itemController.getAllItems();
    itemComboBox.removeAllItems();

    for (Item item : availableItems) {
        itemComboBox.addItem(item.getItemName() + " | Rs." + item.getPrice() + " | Stock: " + item.getStockQuantity());
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    
private ItemController itemController = new ItemController();
private TransactionController transactionController = new TransactionController();
private List<Item> availableItems;
private Transaction currentTransaction = new Transaction();
private DefaultTableModel cartTableModel;
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        itemComboBox = new javax.swing.JComboBox<>();
        quantitySpinner = new javax.swing.JSpinner();
        addToCartButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        cartTable = new javax.swing.JTable();
        totalLabel = new javax.swing.JLabel();
        clearButton = new javax.swing.JButton();
        checkoutButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        itemComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        itemComboBox.addActionListener(this::itemComboBoxActionPerformed);

        addToCartButton.setText("Add to Cart");
        addToCartButton.addActionListener(this::addToCartButtonActionPerformed);

        jLabel1.setText("Item");

        jLabel2.setText("Quantity");

        cartTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Item Name", "Price", "Quantity", "Subtotal"
            }
        ));
        jScrollPane1.setViewportView(cartTable);

        totalLabel.setText("Total: Rs. 0.00");

        clearButton.setText("Clear");
        clearButton.addActionListener(this::clearButtonActionPerformed);

        checkoutButton.setText("Checkout");
        checkoutButton.addActionListener(this::checkoutButtonActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addToCartButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(quantitySpinner)
                                    .addComponent(itemComboBox, 0, 177, Short.MAX_VALUE)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(clearButton)
                            .addComponent(checkoutButton))))
                .addGap(74, 74, 74)
                .addComponent(totalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(199, 199, 199))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(totalLabel)
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(itemComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quantitySpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(addToCartButton)
                .addGap(10, 10, 10)
                .addComponent(checkoutButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(clearButton)
                .addGap(42, 42, 42)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(87, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addToCartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addToCartButtonActionPerformed
        int index = itemComboBox.getSelectedIndex();

    if (index == -1) {
        JOptionPane.showMessageDialog(this, "Please select an item");
        return;
    }

    Item item = availableItems.get(index);
    int qty = (int) quantitySpinner.getValue();

    if (qty <= 0) {
        JOptionPane.showMessageDialog(this, "Quantity must be greater than 0");
        return;
    }

    if (qty > item.getStockQuantity()) {
        JOptionPane.showMessageDialog(this, "Not enough stock");
        return;
    }

    TransactionDetail detail = new TransactionDetail(
            item.getItemId(),
            item.getItemName(),
            qty,
            item.getPrice()
    );

    currentTransaction.getDetails().add(detail);

    cartTableModel.addRow(new Object[]{
        detail.getItemName(),
        detail.getPrice(),
        detail.getQuantity(),
        detail.getSubtotal()
    });

    double total = 0;
    for (TransactionDetail d : currentTransaction.getDetails()) {
        total += d.getSubtotal();
    }

    currentTransaction.setTotalAmount(total);
    totalLabel.setText("Total: Rs. " + String.format("%.2f", total));
    }//GEN-LAST:event_addToCartButtonActionPerformed

    private void itemComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemComboBoxActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
          cartTableModel.setRowCount(0);
    currentTransaction = new Transaction();
    totalLabel.setText("Total: Rs. 0.00");
    quantitySpinner.setValue(1);
    }//GEN-LAST:event_clearButtonActionPerformed

    private void checkoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkoutButtonActionPerformed
        if (currentTransaction.getDetails().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Cart is empty");
        return;
    }

    boolean saved = transactionController.saveTransaction(currentTransaction);

    if (saved) {
        JOptionPane.showMessageDialog(this, "Transaction completed successfully");
        cartTableModel.setRowCount(0);
        currentTransaction = new Transaction();
        totalLabel.setText("Total: Rs. 0.00");
        quantitySpinner.setValue(1);
        loadItems();
    }
    }//GEN-LAST:event_checkoutButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new SalesPanel().setVisible(true));
    }
    
    
    
    

    
    
    
    
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addToCartButton;
    private javax.swing.JTable cartTable;
    private javax.swing.JButton checkoutButton;
    private javax.swing.JButton clearButton;
    private javax.swing.JComboBox<String> itemComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner quantitySpinner;
    private javax.swing.JLabel totalLabel;
    // End of variables declaration//GEN-END:variables
}
